package com.soccer.socevents;

public enum SocEventType {
    AIMING_FINISHED, AIMING_STARTED,
    PLACEING_FINISHED,
    BALLPASSED_GOAL, BALLPASSED_GOALLINE, BALLPASSED_TOUCHLINE,
    BALL_STOPPED, PLAYERS_STOPPED,
    PLAYER_TOUCHED_BALL, PLAYER_TOUCHED_PLAYER
}
