package com.soccer.situations;

public enum RoundState  {
    FIRST_STOP, FIRST_MOVE_AFTER_SECTOR, OPPONENT_MOVE, OPPONENT_COMES, OPPONENT_MOVE_FINISHED, MOVE_WITHOUT_BALL_FINISHED,
    SECOND_MOVE;
}